---
# tasks file for roles/dockerInstall
- name: Disable ipv6
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    reload: true
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_user == 'ubuntu'
- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  when: ansible_user == 'ubuntu'
- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: latest
  when: ansible_user == 'ubuntu'
- name: Install docker
  ansible.builtin.dnf:
    name: docker
    state: present
  when: not ansible_user == 'ubuntu'

- name: Wait (15 seconds) for lock file to clear
  ansible.builtin.pause:
    seconds: 15

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true
  when: ansible_user == 'ubuntu'
- name: Install pip dnf
  ansible.builtin.dnf:
    name: python3-pip
    state: present
    update_cache: true
  when: not ansible_user == 'ubuntu'
- name: Install python requests package
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - requests
    - docker
- name: Enable docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when: ansible_user == 'ubuntu'
- name: Enable podman
  ansible.builtin.service:
    name: podman
    state: started
    enabled: true
  when: not ansible_user == 'ubuntu'

- name: Log into gitlab registry (docker)
  community.docker.docker_login:
    registry_url: registry.gitlab.com
    username: "{{ username }}"
    password: "{{ password }}"
  when: nologin is not defined or not nologin
