---
# tasks file for roles/dockerInstall
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_user == 'ubuntu'
- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  when: ansible_user == 'ubuntu'
- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: latest
  when: ansible_user == 'ubuntu'
- name: Install docker
  ansible.builtin.dnf:
    name: docker
    state: present
  when: not ansible_user == 'ubuntu'

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true
  when: ansible_user == 'ubuntu'
- name: Install pip dnf
  ansible.builtin.dnf:
    name: python3-pip
    state: present
    update_cache: true
  when: not ansible_user == 'ubuntu'
- name: Install python requests package
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - requests
    - docker
- name: Log into gitlab registry
  community.docker.docker_login:
    registry_url: registry.gitlab.com
    username: "{{ username }}"
    password: "{{ password }}"
