---
# tasks file for roles/webhosts
- name: Disable ipv6
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    reload: true
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Pull image
  community.docker.docker_image:
    name: registry.gitlab.com/ikdoeict/kenzo.staelens/2223-iac_docker_project-staelens-kenzo/webserver
    tag: flask-iac
    source: pull

- name: Enable ufw
  community.general.ufw:
    state: enabled

- name: Setup firewall rules
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '8001'
    - '22'
  notify:
    - Restart Firewall

- name: Run image env
  community.docker.docker_container:
    image: registry.gitlab.com/ikdoeict/kenzo.staelens/2223-iac_docker_project-staelens-kenzo/webserver:flask-iac
    ports:
      - 8001:5000
    auto_remove: true
    name: webserver
    env:
      NAME: "{{ envname }}"
  when: envname is defined

- name: Run image no env
  community.docker.docker_container:
    image: registry.gitlab.com/ikdoeict/kenzo.staelens/2223-iac_docker_project-staelens-kenzo/webserver:flask-iac
    ports:
      - 8001:5000
    auto_remove: true
    name: webserver
  when: not envname is defined
