---
# tasks file for roles/loadbalancer
- name: Install docker
  ansible.builtin.dnf:
    name: docker
    state: present

- name: Copy required files
  ansible.builtin.copy:
    src: 'my_files/'
    dest: /dockerfiles
    owner: root
    group: root
    mode: '644'

- name: Ensure openssl
  ansible.builtin.dnf:
    name: openssl
    state: latest

- name: Ensure cryptography
  ansible.builtin.pip:
    name: "cryptography"

- name: Create SSL private key
  community.crypto.openssl_privatekey:
    path: "/dockerfiles/loadbalancer.key"

- name: Generate certificates
  community.crypto.x509_certificate:
    path: "/dockerfiles/loadbalancer.crt"
    privatekey_path: "/dockerfiles/loadbalancer.key"
    provider: selfsigned
    state: present

- name: Loadbalancer template
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /dockerfiles/nginx.conf
    mode: '644'
    owner: root
    group: root

- name: Open port 8000
  ansible.posix.firewalld:
    port: 8000/tcp
    zone: public
    permanent: true
    state: enabled
  notify: Restart Firewall

- name: Pull image
  containers.podman.podman_image:
    name: docker.io/library/nginx
    tag: 1.21.6
    state: present

- name: Enable podman (default docker for RHEL)
  ansible.builtin.service:
    name: podman
    enabled: true
    state: started

- name: Run loadbalancer
  containers.podman.podman_container:
    image: "nginx:1.21.6"
    name: loadbalancer
    auto_remove: true
    ports:
      - 8000:80
    volumes:
      - /dockerfiles:/conf:z
      - /dockerfiles/nginx.conf:/etc/nginx/nginx.conf:ro
