---
# - name: Install docker & workable ansible env
#   hosts: all
#   become: true
#   roles:
#     - common

- name: Controller config
  hosts: controllers
  gather_facts: false
  become: true
  roles: # roles always run before default tasks
    - common 
  tasks:
    - name: Push (force) latest image
      containers.podman.podman_image:
        path: "{{ root }}/ansible/docker_webserver"
        name: registry.gitlab.com/ikdoeict/kenzo.staelens/2223-iac_docker_project-staelens-kenzo/webserver
        tag: flask-iac
        force: true # updates worden zonder force niet gepusht
        push: true
        state: build
        push_args:
          dest: registry.gitlab.com/ikdoeict/kenzo.staelens/2223-iac_docker_project-staelens-kenzo/webserver

- name: Run webservers
  hosts: webservers
  become: true
  roles:
    - common
    - webhosts

- name: Run Loadbalancer
  hosts: loadbalancers
  become: true
  roles:
    - common
    - loadbalancer

- name: Print links
  hosts: localhost
  become: false
  tasks:
    - name: Print links
      ansible.builtin.debug:
        msg: "{{ stage + '_' + hostvars[item]['inventory_hostname'] }}: \
        https://{{ hostvars[item]['ansible_host'] }}:{{ 8000 if item in groups['loadbalancers'] else 8001 }}"
      with_items:
        - "{{ groups['loadbalancers'] + groups['webservers'] }}"
