---
- name: Setup workable ansible/docker environment
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install pip
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install python requests package
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      loop:
        - requests
        - docker
    - name: Log into gitlab registry
      community.docker.docker_login:
        registry_url: registry.gitlab.com
        username: "{{ username }}"
        password: "{{ password }}"
      failed_when: false

- name: Build and push images
  hosts: controllers
  gather_facts: false
  become: true
  tasks:
    - name: Build image
      community.docker.docker_image:
        build:
          path: /home/student/docker_project/2223-iac_docker_project-staelens-kenzo/ansible/docker_content/webserver
        name: registry.gitlab.com/ikdoeict/kenzo.staelens/2223-iac_docker_project-staelens-kenzo/webserver
        tag: flask-iac
        push: true
        source: build

- name: Run webservers
  hosts: webservers
  become: true
  roles:
    - webhosts

- name: Run Loadbalancer
  hosts: loadbalancers
  become: true
  roles:
    - loadbalancer
