---
- name: Disable ubuntu IPv6
  become: true
  hosts: webservers
  tasks:
    - name: Disable ipv6
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        reload: true
      loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6

- name: Install docker & workable ansible env
  hosts: all
  become: true
  roles:
    - common

- name: Build and push images
  hosts: controllers
  gather_facts: false
  become: true
  tasks:
    - name: Push (force) latest image
      containers.podman.podman_image:
        path: "{{ root }}/ansible/docker_webserver"
        name: registry.gitlab.com/ikdoeict/kenzo.staelens/2223-iac_docker_project-staelens-kenzo/webserver
        tag: flask-iac
        force: true # updates worden zonder force niet gepusht
        push: true
        state: build
        push_args:
          dest: registry.gitlab.com/ikdoeict/kenzo.staelens/2223-iac_docker_project-staelens-kenzo/webserver

- name: Run webservers
  hosts: webservers
  become: true
  roles:
    - webhosts

- name: Run Loadbalancer
  hosts: loadbalancers
  become: true
  roles:
    - loadbalancer
