---
- name: Setup docker login
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install pip
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install python requests package
      ansible.builtin.pip:
        name: requests
        state: present

    - name: Log into gitlab registry
      community.docker.docker_login:
        registry_url: registry.gitlab.com
        username: kenzo.staelens@student.odisee.be
        password: "{{ password }}"
      failed_when: false

- name: Build and push images
  hosts: controllers
  gather_facts: false
  become: true
  tasks:
    - name: Build image
      community.docker.docker_image:
        build:
          # /home/student/docker_project/2223-iac_docker_project-staelens-kenzo/ansible/docker_content/webserver
          path: /home/student/docker_project/2223-iac_docker_project-staelens-kenzo/ansible/docker_content/webserver
        name: registry.gitlab.com/ikdoeict/kenzo.staelens/2223-iac_docker_project-staelens-kenzo/webserver
        tag: flask-iac
        push: true
        source: build

- name: Disable ipv6
  hosts: webservers
  become: true
  tasks:
    - name: Set values to disable
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        reload: true
      loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6

- name: Run webservers
  hosts: webservers
  become: true
  roles:
    - webhosts
