---
#test hosts file
all:
  hosts:
  children:
    webservers:
      hosts:
        node1:
          ansible_host: 10.129.24.113
        node2:
          ansible_host: 10.129.24.234
    loadbalancers:
      hosts:
        loadbalancer1:
          ansible_host: 10.129.24.232
    controllers:
      hosts:
        controller1:
          ansible_host: 10.129.24.199
  vars:
    stage: "test"